import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // 为每个板块单独侧边栏（避免点击某一项时看到全部）
  kechengSidebar: [{type: 'autogenerated', dirName: 'kecheng'}],
  jingyanSidebar: [{type: 'autogenerated', dirName: 'jingyan'}],
  qudaoSidebar: [{type: 'autogenerated', dirName: 'qudao'}],
  healthSidebar: [{type: 'autogenerated', dirName: 'health'}],
  careerSidebar: [{type: 'autogenerated', dirName: 'career'}],
  wealthSidebar: [{type: 'autogenerated', dirName: 'wealth'}],
  learningSidebar: [{type: 'autogenerated', dirName: 'learning'}],
  agentSidebar: [
    {
      type: 'category',
      label: '基础篇',
      items: [
        {type: 'doc', id: 'agent/why-agent-era'},
        {type: 'doc', id: 'agent/core-components'},
        {type: 'doc', id: 'agent/how-agent-runs'},
        {type: 'doc', id: 'agent/memory-system'},
        {type: 'doc', id: 'agent/04-5-skill-sop'},
        {type: 'doc', id: 'agent/tool-calling-mcp'},
        {type: 'doc', id: 'agent/agent-runtime'},
        {type: 'doc', id: 'agent/multi-agent'},
        {type: 'doc', id: 'agent/enterprise-architecture'},
        {type: 'doc', id: 'agent/build-from-zero'},
        {type: 'doc', id: 'agent/agent-future'},
        {type: 'doc', id: 'agent/core-terms'},
      ],
    },
    {
      type: 'category',
      label: '进阶篇',
      items: [
        {type: 'doc', id: 'agent/openclaw-hermes'},
        {type: 'doc', id: 'agent/project-practice'},
        {type: 'doc', id: 'agent/tech-stack-roadmap'},
      ],
    },
    {
      type: 'category',
      label: '高级篇',
      items: [{type: 'doc', id: 'agent/advanced-coming-soon'}],
    },
    {
      type: 'category',
      label: '资料篇',
      items: [{type: 'doc', id: 'agent/resources-coming-soon'}],
    },
  ],
  claudeCodeSidebar: [{type: 'autogenerated', dirName: 'claude-code'}],
  imageSidebar: [{type: 'autogenerated', dirName: 'image'}],
  gongjuSidebar: [{type: 'autogenerated', dirName: 'gongju'}],
  shipinSidebar: [{type: 'autogenerated', dirName: 'shipin'}],
  bokeSidebar: [{type: 'autogenerated', dirName: 'boke'}],
  // 书籍独立侧边栏
  shujiSidebar: [{type: 'autogenerated', dirName: 'shuji'}],
};

export default sidebars;
